server:
  port: 5555

spring:
  config:
    import: "optional:classpath:default.yaml"
  application:
    name: user
  datasource:
    url: jdbc:mysql://mysql:3306/letucoj?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 430103535
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379
  mail:
    host: smtp.qq.com
    port: 465
    username: 2878506229@qq.com
    password: whtxpptrfruiddha
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 465

logging:
  level:
    org.springframework.security: DEBUG
    root: INFO
    org.springframework: DEBUG
    com.zaxxer.hikari: DEBUG
    org.mybatis: DEBUG
    com.OMS.practice_service: DEBUG

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.OMS.user_service.repository
  configuration:
    map-underscore-to-camel-case: true

rocketmq:
  name-server: rocketmq-namesrv:9876
  producer:
    group: my-producer-group
  consumer:
    group: my-consumer-group
