server:
  port: 1234

spring:
  config:
    import: "optional:classpath:default.yaml"
  application:
    name: contest
  datasource:
    url: jdbc:mysql://mysql:3306/letucoj?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 430103535
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.OMS.user_service.repository
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    com.zaxxer.hikari: DEBUG
    org.mybatis: DEBUG
    com.OMS.user_service.client: DEBUG

rocketmq:
  name-server: rocketmq-namesrv:9876
  producer:
    group: my-producer-group
  consumer:
    group: my-consumer-group