server:
  port: 2121

spring:
  config:
    import: "optional:classpath:default.yaml"
  application:
    name: sys
  datasource:
    url: jdbc:mysql://mysql:3306/letucoj?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 430103535
    driver-class-name: com.mysql.cj.jdbc.Driver

#logging:
#  level:
#    org.springframework.security: DEBUG
#    root: INFO
#    org.springframework: DEBUG
#    com.zaxxer.hikari: DEBUG
#    org.mybatis: DEBUG
#    com.OMS.practice_service: DEBUG

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.OMS.user_service.repository
  configuration:
    map-underscore-to-camel-case: true

mysql:
  host: mysql
  port: 3306
  user: letuc
  password: 430103535

